############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Sobre"
url = "about/"
weight = 2

# [[main]]
# name = "Cursos"
# url = "elements/"
# weight = 3

[[main]]
weight = 4
name = "Cursos"
hasChildren = true

[[main]]
parent = "Cursos"
name = "Python"
url = "blog/"

[[main]]
parent = "Cursos"
name = "Hugo"
url = "contact/"

[[main]]
parent = "Cursos"
name = "SQL"
url = "authors/"

[[main]]
parent = "Cursos"
name = "Shell Script"
url = "categories/"

[[main]]
parent = "Cursos"
name = "Inglês"
url = "404/"


# footer menu
[[footer]]
name = "About"
url = "about/"
weight = 1

[[footer]]
name = "Elements"
url = "elements/"
weight = 2

[[footer]]
name = "Privacy Policy"
url = "privacy-policy/"
weight = 3
