############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Sobre"
url = "about/"
weight = 2

# [[main]]
# name = "Cursos"
# url = "elements/"
# weight = 3

[[main]]
weight = 4
name = "Cursos"
hasChildren = true

[[main]]
parent = "Cursos"
name = "Python"
# url = "blog/"
url = "https://www.udemy.com/user/algoritmo-aberto/"

[[main]]
parent = "Cursos"
name = "SQL"
# url = "authors/"
url = "https://www.udemy.com/user/algoritmo-aberto/"

[[main]]
parent = "Cursos"
name = "Git"
url = "categories/"
# url = "git/"

[[main]]
parent = "Cursos"
name = "Ver Todos"
url = "authors/"


# footer menu
# [[footer]]
# name = "atendimento@algoritmoaberto.com.br"

# [[footer]]
# name = "About"
# url = "about/"
# weight = 1

# [[footer]]
# name = "Elements"
# url = "elements/"
# weight = 2
 
# [[footer]]
# name = "Privacy Policy"
# url = "privacy-policy/"
# weight = 3
